# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/a/sw/xe/visit/thirdparty/cmake/3.0.2/linux-x86_64_gcc-4.3/bin/cmake

# The command to remove a file.
RM = /mnt/a/sw/xe/visit/thirdparty/cmake/3.0.2/linux-x86_64_gcc-4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /u/sciteam/orf/build/cm1visit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /u/sciteam/orf/build/cm1visit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/mnt/a/sw/xe/visit/thirdparty/cmake/2.8.10.2/linux-x86_64_gcc-4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/mnt/a/sw/xe/visit/thirdparty/cmake/3.0.2/linux-x86_64_gcc-4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /u/sciteam/orf/build/cm1visit/CMakeFiles /u/sciteam/orf/build/cm1visit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /u/sciteam/orf/build/cm1visit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ecm1visitDatabase_par

# Build rule for target.
Ecm1visitDatabase_par: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ecm1visitDatabase_par
.PHONY : Ecm1visitDatabase_par

# fast build rule for target.
Ecm1visitDatabase_par/fast:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/build
.PHONY : Ecm1visitDatabase_par/fast

#=============================================================================
# Target rules for targets named Ecm1visitDatabase_ser

# Build rule for target.
Ecm1visitDatabase_ser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ecm1visitDatabase_ser
.PHONY : Ecm1visitDatabase_ser

# fast build rule for target.
Ecm1visitDatabase_ser/fast:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/build
.PHONY : Ecm1visitDatabase_ser/fast

#=============================================================================
# Target rules for targets named Icm1visitDatabase

# Build rule for target.
Icm1visitDatabase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Icm1visitDatabase
.PHONY : Icm1visitDatabase

# fast build rule for target.
Icm1visitDatabase/fast:
	$(MAKE) -f CMakeFiles/Icm1visitDatabase.dir/build.make CMakeFiles/Icm1visitDatabase.dir/build
.PHONY : Icm1visitDatabase/fast

#=============================================================================
# Target rules for targets named Mcm1visitDatabase

# Build rule for target.
Mcm1visitDatabase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mcm1visitDatabase
.PHONY : Mcm1visitDatabase

# fast build rule for target.
Mcm1visitDatabase/fast:
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/build
.PHONY : Mcm1visitDatabase/fast

avtcm1visitFileFormat.o: avtcm1visitFileFormat.C.o
.PHONY : avtcm1visitFileFormat.o

# target to build an object file
avtcm1visitFileFormat.C.o:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/avtcm1visitFileFormat.C.o
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/avtcm1visitFileFormat.C.o
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/avtcm1visitFileFormat.C.o
.PHONY : avtcm1visitFileFormat.C.o

avtcm1visitFileFormat.i: avtcm1visitFileFormat.C.i
.PHONY : avtcm1visitFileFormat.i

# target to preprocess a source file
avtcm1visitFileFormat.C.i:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/avtcm1visitFileFormat.C.i
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/avtcm1visitFileFormat.C.i
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/avtcm1visitFileFormat.C.i
.PHONY : avtcm1visitFileFormat.C.i

avtcm1visitFileFormat.s: avtcm1visitFileFormat.C.s
.PHONY : avtcm1visitFileFormat.s

# target to generate assembly for a file
avtcm1visitFileFormat.C.s:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/avtcm1visitFileFormat.C.s
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/avtcm1visitFileFormat.C.s
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/avtcm1visitFileFormat.C.s
.PHONY : avtcm1visitFileFormat.C.s

cm1visitCommonPluginInfo.o: cm1visitCommonPluginInfo.C.o
.PHONY : cm1visitCommonPluginInfo.o

# target to build an object file
cm1visitCommonPluginInfo.C.o:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitCommonPluginInfo.C.o
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitCommonPluginInfo.C.o
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitCommonPluginInfo.C.o
.PHONY : cm1visitCommonPluginInfo.C.o

cm1visitCommonPluginInfo.i: cm1visitCommonPluginInfo.C.i
.PHONY : cm1visitCommonPluginInfo.i

# target to preprocess a source file
cm1visitCommonPluginInfo.C.i:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitCommonPluginInfo.C.i
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitCommonPluginInfo.C.i
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitCommonPluginInfo.C.i
.PHONY : cm1visitCommonPluginInfo.C.i

cm1visitCommonPluginInfo.s: cm1visitCommonPluginInfo.C.s
.PHONY : cm1visitCommonPluginInfo.s

# target to generate assembly for a file
cm1visitCommonPluginInfo.C.s:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitCommonPluginInfo.C.s
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitCommonPluginInfo.C.s
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitCommonPluginInfo.C.s
.PHONY : cm1visitCommonPluginInfo.C.s

cm1visitEnginePluginInfo.o: cm1visitEnginePluginInfo.C.o
.PHONY : cm1visitEnginePluginInfo.o

# target to build an object file
cm1visitEnginePluginInfo.C.o:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitEnginePluginInfo.C.o
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitEnginePluginInfo.C.o
.PHONY : cm1visitEnginePluginInfo.C.o

cm1visitEnginePluginInfo.i: cm1visitEnginePluginInfo.C.i
.PHONY : cm1visitEnginePluginInfo.i

# target to preprocess a source file
cm1visitEnginePluginInfo.C.i:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitEnginePluginInfo.C.i
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitEnginePluginInfo.C.i
.PHONY : cm1visitEnginePluginInfo.C.i

cm1visitEnginePluginInfo.s: cm1visitEnginePluginInfo.C.s
.PHONY : cm1visitEnginePluginInfo.s

# target to generate assembly for a file
cm1visitEnginePluginInfo.C.s:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitEnginePluginInfo.C.s
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitEnginePluginInfo.C.s
.PHONY : cm1visitEnginePluginInfo.C.s

cm1visitMDServerPluginInfo.o: cm1visitMDServerPluginInfo.C.o
.PHONY : cm1visitMDServerPluginInfo.o

# target to build an object file
cm1visitMDServerPluginInfo.C.o:
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitMDServerPluginInfo.C.o
.PHONY : cm1visitMDServerPluginInfo.C.o

cm1visitMDServerPluginInfo.i: cm1visitMDServerPluginInfo.C.i
.PHONY : cm1visitMDServerPluginInfo.i

# target to preprocess a source file
cm1visitMDServerPluginInfo.C.i:
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitMDServerPluginInfo.C.i
.PHONY : cm1visitMDServerPluginInfo.C.i

cm1visitMDServerPluginInfo.s: cm1visitMDServerPluginInfo.C.s
.PHONY : cm1visitMDServerPluginInfo.s

# target to generate assembly for a file
cm1visitMDServerPluginInfo.C.s:
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitMDServerPluginInfo.C.s
.PHONY : cm1visitMDServerPluginInfo.C.s

cm1visitPluginInfo.o: cm1visitPluginInfo.C.o
.PHONY : cm1visitPluginInfo.o

# target to build an object file
cm1visitPluginInfo.C.o:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitPluginInfo.C.o
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitPluginInfo.C.o
	$(MAKE) -f CMakeFiles/Icm1visitDatabase.dir/build.make CMakeFiles/Icm1visitDatabase.dir/cm1visitPluginInfo.C.o
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitPluginInfo.C.o
.PHONY : cm1visitPluginInfo.C.o

cm1visitPluginInfo.i: cm1visitPluginInfo.C.i
.PHONY : cm1visitPluginInfo.i

# target to preprocess a source file
cm1visitPluginInfo.C.i:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitPluginInfo.C.i
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitPluginInfo.C.i
	$(MAKE) -f CMakeFiles/Icm1visitDatabase.dir/build.make CMakeFiles/Icm1visitDatabase.dir/cm1visitPluginInfo.C.i
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitPluginInfo.C.i
.PHONY : cm1visitPluginInfo.C.i

cm1visitPluginInfo.s: cm1visitPluginInfo.C.s
.PHONY : cm1visitPluginInfo.s

# target to generate assembly for a file
cm1visitPluginInfo.C.s:
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_par.dir/build.make CMakeFiles/Ecm1visitDatabase_par.dir/cm1visitPluginInfo.C.s
	$(MAKE) -f CMakeFiles/Ecm1visitDatabase_ser.dir/build.make CMakeFiles/Ecm1visitDatabase_ser.dir/cm1visitPluginInfo.C.s
	$(MAKE) -f CMakeFiles/Icm1visitDatabase.dir/build.make CMakeFiles/Icm1visitDatabase.dir/cm1visitPluginInfo.C.s
	$(MAKE) -f CMakeFiles/Mcm1visitDatabase.dir/build.make CMakeFiles/Mcm1visitDatabase.dir/cm1visitPluginInfo.C.s
.PHONY : cm1visitPluginInfo.C.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Ecm1visitDatabase_par"
	@echo "... Ecm1visitDatabase_ser"
	@echo "... Icm1visitDatabase"
	@echo "... Mcm1visitDatabase"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... avtcm1visitFileFormat.o"
	@echo "... avtcm1visitFileFormat.i"
	@echo "... avtcm1visitFileFormat.s"
	@echo "... cm1visitCommonPluginInfo.o"
	@echo "... cm1visitCommonPluginInfo.i"
	@echo "... cm1visitCommonPluginInfo.s"
	@echo "... cm1visitEnginePluginInfo.o"
	@echo "... cm1visitEnginePluginInfo.i"
	@echo "... cm1visitEnginePluginInfo.s"
	@echo "... cm1visitMDServerPluginInfo.o"
	@echo "... cm1visitMDServerPluginInfo.i"
	@echo "... cm1visitMDServerPluginInfo.s"
	@echo "... cm1visitPluginInfo.o"
	@echo "... cm1visitPluginInfo.i"
	@echo "... cm1visitPluginInfo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

